### ISSUE TITLE
Haranoaji K1でのU+2018

### ISSUE THREAD

**Issue by t-tk** [trueroad/HaranoAjiFontsK1#1]
お世話になります。
以前からの懸案、japanese-otf-uptex に中韓の本文用フォントを追加しようと試しています。
https://github.com/t-tk/japanese-otf-uptex/issues/7

HaranoAjiMinchoK1-Regular.otf を使って U+2018 「‘」を出そうとすると見つからないといわれます。
```
dvipdfmx:warning: No character mapping available.
 CMap name: HaranoAjiMinchoK1-Regular.otf,000-UCS4-H
 input str: <00002018>
]
```
Adobe-Korea1-2 では U+2018 は CID114 にマップされて`いるようなので、Haranoaji K1 でも出る想定に対し意外な結果でした。
HaranoAjiMinchoK1-Regular.otf で見つからない理由がもし分かったら教えてください。

参考:
https://github.com/texjporg/uptex-fonts/blob/master/source/punctuation.md

**Comment by trueroad** [comment]
ご指摘いただきありがとうございます。
直接的には HaranoAjiMinchoK1 20220130 版が AK1 CID+114 を搭載していないため U+2018 が無いということになります。

ではなぜ AK1 CID+114 を搭載していないか調べてみました。
まず、SourceHanSerifKR-Regular 2.001 の cmap テーブルを抜粋すると以下のマッピングがあります。

* U+02BB -> AI0 CID+725
* U+2018 -> AI0 CID+725

複数の Unicode コードポイントが同一の CID を指定しているため、
HaranoAjiFonts-generator 20220130 版は若番の U+02BB を優先します。
（部首など一部のコードポイントは若番であっても優先しないようにはしてあります）

次に CMap の UniKS-UTF32-H のマッピングを見ると以下のマッピングはありましたが、
U+02BB のマッピングがありませんでした。

* U+2018 -> AK1 CID+114

すると、HaranoAjiFonts-generator は U+02BB が無いため
AI0 CID+725 の変換先となる AK1 CID を見つけることができずグリフを捨ててしまい、
AK1 CID+114 が搭載されていない状態になった、ということがわかりました。

よって、源ノフォントで複数の Unicode コードポイントが同一の CID を指定している際に、
単純に若番を優先するのではなくて使用する CMap に存在する方を優先する
（両方とも存在する場合は若番を優先する）ことで改良できそうに思っています。

なお、 K1 以外がどうなっているのか調べてみたところ、

* JP
    + CMap UniJIS2004-UTF32-H に U+02BB が存在していて U+2018 と同じ AJ1 CID+98 を指しているので結果的に問題なし
* CN, TW
    + SourceHanSerif の AI0 CID が U+02BB と U+2018 で独立しているため U+2018 側の CID が割り当てられて問題なし
* KR
    + K1 と同様で U+2018 が無い

というようになっておりました。

**Comment by t-tk** [comment]
早速のご調査ありがとうございます。
https://github.com/t-tk/japanese-otf-uptex/issues/7 の方のissueではなさそうなので、こちらはそのまま進めることにします。

**Comment by trueroad** [comment]
[20220211 版](https://github.com/trueroad/HaranoAjiFontsK1/releases/tag/20220211)で U+2018 を搭載しました。ご確認ください。

**Comment by t-tk** [comment]
ありがとうございます。U+2018が出るようになりました。
また、以前の版でU+3008, U+3009も欠けていたようですが、これらも出るようになりました。
助かります。

**Comment by trueroad** [comment]
ご確認ありがとうございます。出るようになったとのことなのでクローズします。
