### ISSUE TITLE
UniKS-UTF16-V経由の「！」「？」

### ISSUE THREAD

**Issue by t-tk** [trueroad/HaranoAjiFontsK1#2]
https://github.com/trueroad/HaranoAjiFontsCN/issues/1 にもう一点追加です。K1固有なのでこちらに書きます。
K1 の縦組みで`UniKS-UTF16-V` を指定しCID経由で出力しようとした場合、全角の「！」(U+FF01),「？」(U+FF1F)が出ないようです。(Unicode指定ではちゃんと出るのですが)
これも該当CIDのグリフが SourceHan に存在しないという理解で合っていますか?
( No Tofu のはずが… )

テストサンプルは↓
https://github.com/t-tk/japanese-otf-uptex/tree/ck-basefont/japanese-otf-uptex/test/uplatex

`make mltwght` で生成したpdfのうちの `chk-mltwght-v-cmap.pdf` です。

![image](https://user-images.githubusercontent.com/3814120/154072681-55cb80c2-d578-43d8-9d3c-7dbbd68c17d6.png)

**Comment by trueroad** [comment]
> K1 の縦組みでUniKS-UTF16-V を指定しCID経由で出力しようとした場合、全角の「！」(U+FF01),「？」(U+FF1F)が出ないようです。(Unicode指定ではちゃんと出るのですが)
> これも該当CIDのグリフが SourceHan に存在しないという理解で合っていますか?
> ( No Tofu のはずが… )

U+FF01, U+FF1F の縦書き用グリフは SourceHan{Serif|Sans}KR に存在するようです。
HaranoAjiFonts-generator は SourceHan の GSUB vert 先の AI0 CID と AK1 CID を紐づけようとしますが、これがうまくいっておらずに U+FF01, U+FF1F の縦書き CID を紐づけできていないようです。

SourceHanSerifKR 2.001 の場合ですが cmap テーブルには

U+FF01 -> AI0 CID+58949
U+FF1F -> AI0 CID+58979

というマッピングがあります。GSUB の vert には

AI0 CID+58949 -> AI0 CID+58886
AI0 CID+58979 -> AI0 CID+58887

があるのですが、他に

AI0 CID+63029 -> AI0 CID+58886
AI0 CID+63034 -> AI0 CID+58887

というマッピングもあって vert の元が重複しているため紐づけに失敗しているようです。

**Comment by trueroad** [comment]
とりあえず修正をしてみたところ以下のように CN で 1 グリフ、K1 で 4 グリフ、収録グリフが増加しました。

CN: AG1 CID+817
K1: AK1 CID+8081, CID+8082, CID+8076, CID+8086

本件は AK1 CID+8076, CID+8086 の欠落によるものなのでこれで解決できそうです。
JP, TW, KR についてはグリフ数の変化はありませんでした。

後日になりますが諸々確認してから CN と K1 のみ修正版をリリースしようかと思います。

**Comment by t-tk** [comment]
ありがとうございます。
リリースされたらテストしたいと思います。

**Comment by t-tk** [comment]
UniKS-UTF16-Vにある以下もUnicode経由では出るがCID経由で出ないように見えます。一緒に見ていただけるとよいかと。
U+2013  CID8059
U+2014  CID8060

**Comment by trueroad** [comment]
残念ながら SourceHanSerifKR 2.001, SourceHanSansKR 2.004 は U+2013, U+2014 の縦組みグリフを搭載していないようです。

**Comment by t-tk** [comment]
了解しました。ご確認ありがとうございました。

**Comment by trueroad** [comment]
20220220版で修正いたしました。
ご確認ください。

**Comment by t-tk** [comment]
ありがとうございます。20220220版で組んでみました。
全角の「！」(U+FF01),「？」(U+FF1F) は縦組みでも出るようになりました。
ただしグリフの位置が右に寄っています。私の直感には反していますが正しいのかどうか分かりません。
U+2025, U+2026はTWの方に述べた通りです。
https://github.com/trueroad/HaranoAjiFontsTW/issues/1#issuecomment-1046212532
U+2013, U+2014 は縦組みグリフが無いとのこと、納得しています。

![image](https://user-images.githubusercontent.com/3814120/154840086-1804a536-d413-45e7-b1d0-440ad64e0037.png)

**Comment by trueroad** [comment]
ご確認いただきありがとうございます。

> 全角の「！」(U+FF01),「？」(U+FF1F) は縦組みでも出るようになりました。
> ただしグリフの位置が右に寄っています。私の直感には反していますが正しいのかどうか分かりません。

Adobe の AK1 グリフ一覧が載っているドキュメント
5093.Adobe-Korea1-2.pdf
を見ると AK1 CID+8076, AK1 CID+8086 （全角縦組み用「！」「？」）はいずれもグリフの位置が右に寄っています。

また、SourceHanSerifReadMe.pdf 2.001 の p. 24-25 を見ると、Korean では該当グリフが右に寄るようになっています。

ですので韓国語における縦組み組版ではそういう習慣なんだろうと理解しています。

**Comment by t-tk** [comment]
ご回答ありがとうございます。
本件はここまでにしたいと思います。
